// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thirtyfive.proto

package thirtyfive

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShipmentStatus int32

const (
	ShipmentStatus_ShipmentStatus_UNKNOWN            ShipmentStatus = 0
	ShipmentStatus_ShipmentStatus_PRETRANSIT         ShipmentStatus = 1
	ShipmentStatus_ShipmentStatus_INTRANSIT          ShipmentStatus = 2
	ShipmentStatus_ShipmentStatus_OUTFORDELIVERY     ShipmentStatus = 3
	ShipmentStatus_ShipmentStatus_DELIVERED          ShipmentStatus = 4
	ShipmentStatus_ShipmentStatus_AVAILABLEFORPICKUP ShipmentStatus = 5
	ShipmentStatus_ShipmentStatus_RETURNTOSENDER     ShipmentStatus = 6
	ShipmentStatus_ShipmentStatus_FAILURE            ShipmentStatus = 7
	ShipmentStatus_ShipmentStatus_CANCELLED          ShipmentStatus = 8
	ShipmentStatus_ShipmentStatus_ERROR              ShipmentStatus = 9
)

var ShipmentStatus_name = map[int32]string{
	0: "ShipmentStatus_UNKNOWN",
	1: "ShipmentStatus_PRETRANSIT",
	2: "ShipmentStatus_INTRANSIT",
	3: "ShipmentStatus_OUTFORDELIVERY",
	4: "ShipmentStatus_DELIVERED",
	5: "ShipmentStatus_AVAILABLEFORPICKUP",
	6: "ShipmentStatus_RETURNTOSENDER",
	7: "ShipmentStatus_FAILURE",
	8: "ShipmentStatus_CANCELLED",
	9: "ShipmentStatus_ERROR",
}
var ShipmentStatus_value = map[string]int32{
	"ShipmentStatus_UNKNOWN":            0,
	"ShipmentStatus_PRETRANSIT":         1,
	"ShipmentStatus_INTRANSIT":          2,
	"ShipmentStatus_OUTFORDELIVERY":     3,
	"ShipmentStatus_DELIVERED":          4,
	"ShipmentStatus_AVAILABLEFORPICKUP": 5,
	"ShipmentStatus_RETURNTOSENDER":     6,
	"ShipmentStatus_FAILURE":            7,
	"ShipmentStatus_CANCELLED":          8,
	"ShipmentStatus_ERROR":              9,
}

func (x ShipmentStatus) String() string {
	return proto.EnumName(ShipmentStatus_name, int32(x))
}
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{0}
}

type ShipmentType int32

const (
	ShipmentType_ShipmentType_ACCESS ShipmentType = 0
	ShipmentType_ShipmentType_EARN   ShipmentType = 1
)

var ShipmentType_name = map[int32]string{
	0: "ShipmentType_ACCESS",
	1: "ShipmentType_EARN",
}
var ShipmentType_value = map[string]int32{
	"ShipmentType_ACCESS": 0,
	"ShipmentType_EARN":   1,
}

func (x ShipmentType) String() string {
	return proto.EnumName(ShipmentType_name, int32(x))
}
func (ShipmentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{1}
}

type ShipmentDirection int32

const (
	ShipmentDirection_ShipmentDirection_INBOUND  ShipmentDirection = 0
	ShipmentDirection_ShipmentDirection_OUTBOUND ShipmentDirection = 1
)

var ShipmentDirection_name = map[int32]string{
	0: "ShipmentDirection_INBOUND",
	1: "ShipmentDirection_OUTBOUND",
}
var ShipmentDirection_value = map[string]int32{
	"ShipmentDirection_INBOUND":  0,
	"ShipmentDirection_OUTBOUND": 1,
}

func (x ShipmentDirection) String() string {
	return proto.EnumName(ShipmentDirection_name, int32(x))
}
func (ShipmentDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{2}
}

type InventoryCondition int32

const (
	InventoryCondition_InventoryCondition_NEW       InventoryCondition = 0
	InventoryCondition_InventoryCondition_LIKENEW   InventoryCondition = 1
	InventoryCondition_InventoryCondition_EXCELLENT InventoryCondition = 2
	InventoryCondition_InventoryCondition_USED      InventoryCondition = 3
	InventoryCondition_InventoryCondition_DAMAGED   InventoryCondition = 4
)

var InventoryCondition_name = map[int32]string{
	0: "InventoryCondition_NEW",
	1: "InventoryCondition_LIKENEW",
	2: "InventoryCondition_EXCELLENT",
	3: "InventoryCondition_USED",
	4: "InventoryCondition_DAMAGED",
}
var InventoryCondition_value = map[string]int32{
	"InventoryCondition_NEW":       0,
	"InventoryCondition_LIKENEW":   1,
	"InventoryCondition_EXCELLENT": 2,
	"InventoryCondition_USED":      3,
	"InventoryCondition_DAMAGED":   4,
}

func (x InventoryCondition) String() string {
	return proto.EnumName(InventoryCondition_name, int32(x))
}
func (InventoryCondition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{3}
}

type InventoryStatus int32

const (
	InventoryStatus_InventoryStatus_NEW              InventoryStatus = 0
	InventoryStatus_InventoryStatus_PENDING          InventoryStatus = 1
	InventoryStatus_InventoryStatus_ACCEPTED         InventoryStatus = 2
	InventoryStatus_InventoryStatus_ENROUTEWAREHOUSE InventoryStatus = 3
	InventoryStatus_InventoryStatus_INSPECTING       InventoryStatus = 4
	InventoryStatus_InventoryStatus_INWAREHOUSE      InventoryStatus = 5
	InventoryStatus_InventoryStatus_SHIPMENTPREP     InventoryStatus = 6
	InventoryStatus_InventoryStatus_ENROUTEMEMBER    InventoryStatus = 7
	InventoryStatus_InventoryStatus_WITHMEMBER       InventoryStatus = 8
	InventoryStatus_InventoryStatus_RETURNING        InventoryStatus = 9
	InventoryStatus_InventoryStatus_OUTOFSERVICE     InventoryStatus = 10
	InventoryStatus_InventoryStatus_ENROUTEOWNER     InventoryStatus = 11
	InventoryStatus_InventoryStatus_RETURNED         InventoryStatus = 12
	InventoryStatus_InventoryStatus_STOLEN           InventoryStatus = 13
	InventoryStatus_InventoryStatus_LOST             InventoryStatus = 14
)

var InventoryStatus_name = map[int32]string{
	0:  "InventoryStatus_NEW",
	1:  "InventoryStatus_PENDING",
	2:  "InventoryStatus_ACCEPTED",
	3:  "InventoryStatus_ENROUTEWAREHOUSE",
	4:  "InventoryStatus_INSPECTING",
	5:  "InventoryStatus_INWAREHOUSE",
	6:  "InventoryStatus_SHIPMENTPREP",
	7:  "InventoryStatus_ENROUTEMEMBER",
	8:  "InventoryStatus_WITHMEMBER",
	9:  "InventoryStatus_RETURNING",
	10: "InventoryStatus_OUTOFSERVICE",
	11: "InventoryStatus_ENROUTEOWNER",
	12: "InventoryStatus_RETURNED",
	13: "InventoryStatus_STOLEN",
	14: "InventoryStatus_LOST",
}
var InventoryStatus_value = map[string]int32{
	"InventoryStatus_NEW":              0,
	"InventoryStatus_PENDING":          1,
	"InventoryStatus_ACCEPTED":         2,
	"InventoryStatus_ENROUTEWAREHOUSE": 3,
	"InventoryStatus_INSPECTING":       4,
	"InventoryStatus_INWAREHOUSE":      5,
	"InventoryStatus_SHIPMENTPREP":     6,
	"InventoryStatus_ENROUTEMEMBER":    7,
	"InventoryStatus_WITHMEMBER":       8,
	"InventoryStatus_RETURNING":        9,
	"InventoryStatus_OUTOFSERVICE":     10,
	"InventoryStatus_ENROUTEOWNER":     11,
	"InventoryStatus_RETURNED":         12,
	"InventoryStatus_STOLEN":           13,
	"InventoryStatus_LOST":             14,
}

func (x InventoryStatus) String() string {
	return proto.EnumName(InventoryStatus_name, int32(x))
}
func (InventoryStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{4}
}

type Shipment struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EstDeliveryDate      *timestamp.Timestamp `protobuf:"bytes,2,opt,name=est_delivery_date,json=estDeliveryDate,proto3" json:"est_delivery_date,omitempty"`
	InventoryCount       int32                `protobuf:"varint,3,opt,name=inventory_count,json=inventoryCount,proto3" json:"inventory_count,omitempty"`
	Status               ShipmentStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=thirtyfive.ShipmentStatus" json:"status,omitempty"`
	Direction            ShipmentDirection    `protobuf:"varint,5,opt,name=direction,proto3,enum=thirtyfive.ShipmentDirection" json:"direction,omitempty"`
	Type                 ShipmentType         `protobuf:"varint,6,opt,name=type,proto3,enum=thirtyfive.ShipmentType" json:"type,omitempty"`
	Inventory            []*Inventory         `protobuf:"bytes,7,rep,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Shipment) Reset()         { *m = Shipment{} }
func (m *Shipment) String() string { return proto.CompactTextString(m) }
func (*Shipment) ProtoMessage()    {}
func (*Shipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{0}
}
func (m *Shipment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shipment.Unmarshal(m, b)
}
func (m *Shipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shipment.Marshal(b, m, deterministic)
}
func (dst *Shipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipment.Merge(dst, src)
}
func (m *Shipment) XXX_Size() int {
	return xxx_messageInfo_Shipment.Size(m)
}
func (m *Shipment) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipment.DiscardUnknown(m)
}

var xxx_messageInfo_Shipment proto.InternalMessageInfo

func (m *Shipment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Shipment) GetEstDeliveryDate() *timestamp.Timestamp {
	if m != nil {
		return m.EstDeliveryDate
	}
	return nil
}

func (m *Shipment) GetInventoryCount() int32 {
	if m != nil {
		return m.InventoryCount
	}
	return 0
}

func (m *Shipment) GetStatus() ShipmentStatus {
	if m != nil {
		return m.Status
	}
	return ShipmentStatus_ShipmentStatus_UNKNOWN
}

func (m *Shipment) GetDirection() ShipmentDirection {
	if m != nil {
		return m.Direction
	}
	return ShipmentDirection_ShipmentDirection_INBOUND
}

func (m *Shipment) GetType() ShipmentType {
	if m != nil {
		return m.Type
	}
	return ShipmentType_ShipmentType_ACCESS
}

func (m *Shipment) GetInventory() []*Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

type ShipmentNode struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Record               *Shipment `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ShipmentNode) Reset()         { *m = ShipmentNode{} }
func (m *ShipmentNode) String() string { return proto.CompactTextString(m) }
func (*ShipmentNode) ProtoMessage()    {}
func (*ShipmentNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{1}
}
func (m *ShipmentNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentNode.Unmarshal(m, b)
}
func (m *ShipmentNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentNode.Marshal(b, m, deterministic)
}
func (dst *ShipmentNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentNode.Merge(dst, src)
}
func (m *ShipmentNode) XXX_Size() int {
	return xxx_messageInfo_ShipmentNode.Size(m)
}
func (m *ShipmentNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentNode.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentNode proto.InternalMessageInfo

func (m *ShipmentNode) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShipmentNode) GetRecord() *Shipment {
	if m != nil {
		return m.Record
	}
	return nil
}

type Inventory struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bin                  string             `protobuf:"bytes,2,opt,name=bin,proto3" json:"bin,omitempty"`
	Serial               string             `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	User                 *User              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Status               InventoryStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=thirtyfive.InventoryStatus" json:"status,omitempty"`
	Condition            InventoryCondition `protobuf:"varint,6,opt,name=condition,proto3,enum=thirtyfive.InventoryCondition" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{2}
}
func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (dst *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(dst, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Inventory) GetBin() string {
	if m != nil {
		return m.Bin
	}
	return ""
}

func (m *Inventory) GetSerial() string {
	if m != nil {
		return m.Serial
	}
	return ""
}

func (m *Inventory) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Inventory) GetStatus() InventoryStatus {
	if m != nil {
		return m.Status
	}
	return InventoryStatus_InventoryStatus_NEW
}

func (m *Inventory) GetCondition() InventoryCondition {
	if m != nil {
		return m.Condition
	}
	return InventoryCondition_InventoryCondition_NEW
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Inspection struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Functionality        int32              `protobuf:"varint,2,opt,name=functionality,proto3" json:"functionality,omitempty"`
	Aethestic            int32              `protobuf:"varint,3,opt,name=aethestic,proto3" json:"aethestic,omitempty"`
	Image                string             `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Notes                string             `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	Condition            InventoryCondition `protobuf:"varint,6,opt,name=condition,proto3,enum=thirtyfive.InventoryCondition" json:"condition,omitempty"`
	InventoryId          string             `protobuf:"bytes,7,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	ShipmentId           string             `protobuf:"bytes,8,opt,name=shipmentId,proto3" json:"shipmentId,omitempty"`
	Tasks                string             `protobuf:"bytes,9,opt,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Inspection) Reset()         { *m = Inspection{} }
func (m *Inspection) String() string { return proto.CompactTextString(m) }
func (*Inspection) ProtoMessage()    {}
func (*Inspection) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{4}
}
func (m *Inspection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inspection.Unmarshal(m, b)
}
func (m *Inspection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inspection.Marshal(b, m, deterministic)
}
func (dst *Inspection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inspection.Merge(dst, src)
}
func (m *Inspection) XXX_Size() int {
	return xxx_messageInfo_Inspection.Size(m)
}
func (m *Inspection) XXX_DiscardUnknown() {
	xxx_messageInfo_Inspection.DiscardUnknown(m)
}

var xxx_messageInfo_Inspection proto.InternalMessageInfo

func (m *Inspection) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Inspection) GetFunctionality() int32 {
	if m != nil {
		return m.Functionality
	}
	return 0
}

func (m *Inspection) GetAethestic() int32 {
	if m != nil {
		return m.Aethestic
	}
	return 0
}

func (m *Inspection) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Inspection) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Inspection) GetCondition() InventoryCondition {
	if m != nil {
		return m.Condition
	}
	return InventoryCondition_InventoryCondition_NEW
}

func (m *Inspection) GetInventoryId() string {
	if m != nil {
		return m.InventoryId
	}
	return ""
}

func (m *Inspection) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *Inspection) GetTasks() string {
	if m != nil {
		return m.Tasks
	}
	return ""
}

type GetShipmentsRequest struct {
	Order                string   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Column               string   `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipmentsRequest) Reset()         { *m = GetShipmentsRequest{} }
func (m *GetShipmentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetShipmentsRequest) ProtoMessage()    {}
func (*GetShipmentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{5}
}
func (m *GetShipmentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentsRequest.Unmarshal(m, b)
}
func (m *GetShipmentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentsRequest.Marshal(b, m, deterministic)
}
func (dst *GetShipmentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentsRequest.Merge(dst, src)
}
func (m *GetShipmentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetShipmentsRequest.Size(m)
}
func (m *GetShipmentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentsRequest proto.InternalMessageInfo

func (m *GetShipmentsRequest) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *GetShipmentsRequest) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

type GetShipmentsReply struct {
	Shipments            []*Shipment `protobuf:"bytes,1,rep,name=shipments,proto3" json:"shipments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetShipmentsReply) Reset()         { *m = GetShipmentsReply{} }
func (m *GetShipmentsReply) String() string { return proto.CompactTextString(m) }
func (*GetShipmentsReply) ProtoMessage()    {}
func (*GetShipmentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{6}
}
func (m *GetShipmentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentsReply.Unmarshal(m, b)
}
func (m *GetShipmentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentsReply.Marshal(b, m, deterministic)
}
func (dst *GetShipmentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentsReply.Merge(dst, src)
}
func (m *GetShipmentsReply) XXX_Size() int {
	return xxx_messageInfo_GetShipmentsReply.Size(m)
}
func (m *GetShipmentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentsReply proto.InternalMessageInfo

func (m *GetShipmentsReply) GetShipments() []*Shipment {
	if m != nil {
		return m.Shipments
	}
	return nil
}

type GetShipmentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipmentRequest) Reset()         { *m = GetShipmentRequest{} }
func (m *GetShipmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetShipmentRequest) ProtoMessage()    {}
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{7}
}
func (m *GetShipmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentRequest.Unmarshal(m, b)
}
func (m *GetShipmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentRequest.Marshal(b, m, deterministic)
}
func (dst *GetShipmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentRequest.Merge(dst, src)
}
func (m *GetShipmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetShipmentRequest.Size(m)
}
func (m *GetShipmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentRequest proto.InternalMessageInfo

func (m *GetShipmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetShipmentReply struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shipment             *Shipment `protobuf:"bytes,2,opt,name=shipment,proto3" json:"shipment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetShipmentReply) Reset()         { *m = GetShipmentReply{} }
func (m *GetShipmentReply) String() string { return proto.CompactTextString(m) }
func (*GetShipmentReply) ProtoMessage()    {}
func (*GetShipmentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{8}
}
func (m *GetShipmentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipmentReply.Unmarshal(m, b)
}
func (m *GetShipmentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipmentReply.Marshal(b, m, deterministic)
}
func (dst *GetShipmentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipmentReply.Merge(dst, src)
}
func (m *GetShipmentReply) XXX_Size() int {
	return xxx_messageInfo_GetShipmentReply.Size(m)
}
func (m *GetShipmentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipmentReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipmentReply proto.InternalMessageInfo

func (m *GetShipmentReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetShipmentReply) GetShipment() *Shipment {
	if m != nil {
		return m.Shipment
	}
	return nil
}

type CreateInspectionRequest struct {
	Functionality        int32              `protobuf:"varint,1,opt,name=functionality,proto3" json:"functionality,omitempty"`
	Aethestic            int32              `protobuf:"varint,2,opt,name=aethestic,proto3" json:"aethestic,omitempty"`
	Image                string             `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Notes                string             `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Condition            InventoryCondition `protobuf:"varint,5,opt,name=condition,proto3,enum=thirtyfive.InventoryCondition" json:"condition,omitempty"`
	InventoryId          string             `protobuf:"bytes,6,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	ShipmentId           string             `protobuf:"bytes,7,opt,name=shipmentId,proto3" json:"shipmentId,omitempty"`
	Tasks                []string           `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreateInspectionRequest) Reset()         { *m = CreateInspectionRequest{} }
func (m *CreateInspectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateInspectionRequest) ProtoMessage()    {}
func (*CreateInspectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{9}
}
func (m *CreateInspectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateInspectionRequest.Unmarshal(m, b)
}
func (m *CreateInspectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateInspectionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateInspectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateInspectionRequest.Merge(dst, src)
}
func (m *CreateInspectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateInspectionRequest.Size(m)
}
func (m *CreateInspectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateInspectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateInspectionRequest proto.InternalMessageInfo

func (m *CreateInspectionRequest) GetFunctionality() int32 {
	if m != nil {
		return m.Functionality
	}
	return 0
}

func (m *CreateInspectionRequest) GetAethestic() int32 {
	if m != nil {
		return m.Aethestic
	}
	return 0
}

func (m *CreateInspectionRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateInspectionRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *CreateInspectionRequest) GetCondition() InventoryCondition {
	if m != nil {
		return m.Condition
	}
	return InventoryCondition_InventoryCondition_NEW
}

func (m *CreateInspectionRequest) GetInventoryId() string {
	if m != nil {
		return m.InventoryId
	}
	return ""
}

func (m *CreateInspectionRequest) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *CreateInspectionRequest) GetTasks() []string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type UpdateInspectionRequest struct {
	Functionality        int32              `protobuf:"varint,1,opt,name=functionality,proto3" json:"functionality,omitempty"`
	Aethestic            int32              `protobuf:"varint,2,opt,name=aethestic,proto3" json:"aethestic,omitempty"`
	Image                string             `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Notes                string             `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Condition            InventoryCondition `protobuf:"varint,5,opt,name=condition,proto3,enum=thirtyfive.InventoryCondition" json:"condition,omitempty"`
	InventoryId          string             `protobuf:"bytes,6,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	ShipmentId           string             `protobuf:"bytes,7,opt,name=shipmentId,proto3" json:"shipmentId,omitempty"`
	Tasks                []string           `protobuf:"bytes,8,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateInspectionRequest) Reset()         { *m = UpdateInspectionRequest{} }
func (m *UpdateInspectionRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInspectionRequest) ProtoMessage()    {}
func (*UpdateInspectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{10}
}
func (m *UpdateInspectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInspectionRequest.Unmarshal(m, b)
}
func (m *UpdateInspectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInspectionRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateInspectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInspectionRequest.Merge(dst, src)
}
func (m *UpdateInspectionRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInspectionRequest.Size(m)
}
func (m *UpdateInspectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInspectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInspectionRequest proto.InternalMessageInfo

func (m *UpdateInspectionRequest) GetFunctionality() int32 {
	if m != nil {
		return m.Functionality
	}
	return 0
}

func (m *UpdateInspectionRequest) GetAethestic() int32 {
	if m != nil {
		return m.Aethestic
	}
	return 0
}

func (m *UpdateInspectionRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpdateInspectionRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *UpdateInspectionRequest) GetCondition() InventoryCondition {
	if m != nil {
		return m.Condition
	}
	return InventoryCondition_InventoryCondition_NEW
}

func (m *UpdateInspectionRequest) GetInventoryId() string {
	if m != nil {
		return m.InventoryId
	}
	return ""
}

func (m *UpdateInspectionRequest) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *UpdateInspectionRequest) GetTasks() []string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type ReleaseInventoryRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseInventoryRequest) Reset()         { *m = ReleaseInventoryRequest{} }
func (m *ReleaseInventoryRequest) String() string { return proto.CompactTextString(m) }
func (*ReleaseInventoryRequest) ProtoMessage()    {}
func (*ReleaseInventoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{11}
}
func (m *ReleaseInventoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseInventoryRequest.Unmarshal(m, b)
}
func (m *ReleaseInventoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseInventoryRequest.Marshal(b, m, deterministic)
}
func (dst *ReleaseInventoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseInventoryRequest.Merge(dst, src)
}
func (m *ReleaseInventoryRequest) XXX_Size() int {
	return xxx_messageInfo_ReleaseInventoryRequest.Size(m)
}
func (m *ReleaseInventoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseInventoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseInventoryRequest proto.InternalMessageInfo

func (m *ReleaseInventoryRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ReleaseInventoryReply struct {
	Inventory            []*Inventory `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReleaseInventoryReply) Reset()         { *m = ReleaseInventoryReply{} }
func (m *ReleaseInventoryReply) String() string { return proto.CompactTextString(m) }
func (*ReleaseInventoryReply) ProtoMessage()    {}
func (*ReleaseInventoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_thirtyfive_af9745d5c07ca156, []int{12}
}
func (m *ReleaseInventoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseInventoryReply.Unmarshal(m, b)
}
func (m *ReleaseInventoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseInventoryReply.Marshal(b, m, deterministic)
}
func (dst *ReleaseInventoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseInventoryReply.Merge(dst, src)
}
func (m *ReleaseInventoryReply) XXX_Size() int {
	return xxx_messageInfo_ReleaseInventoryReply.Size(m)
}
func (m *ReleaseInventoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseInventoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseInventoryReply proto.InternalMessageInfo

func (m *ReleaseInventoryReply) GetInventory() []*Inventory {
	if m != nil {
		return m.Inventory
	}
	return nil
}

func init() {
	proto.RegisterType((*Shipment)(nil), "thirtyfive.Shipment")
	proto.RegisterType((*ShipmentNode)(nil), "thirtyfive.ShipmentNode")
	proto.RegisterType((*Inventory)(nil), "thirtyfive.Inventory")
	proto.RegisterType((*User)(nil), "thirtyfive.User")
	proto.RegisterType((*Inspection)(nil), "thirtyfive.Inspection")
	proto.RegisterType((*GetShipmentsRequest)(nil), "thirtyfive.GetShipmentsRequest")
	proto.RegisterType((*GetShipmentsReply)(nil), "thirtyfive.GetShipmentsReply")
	proto.RegisterType((*GetShipmentRequest)(nil), "thirtyfive.GetShipmentRequest")
	proto.RegisterType((*GetShipmentReply)(nil), "thirtyfive.GetShipmentReply")
	proto.RegisterType((*CreateInspectionRequest)(nil), "thirtyfive.CreateInspectionRequest")
	proto.RegisterType((*UpdateInspectionRequest)(nil), "thirtyfive.UpdateInspectionRequest")
	proto.RegisterType((*ReleaseInventoryRequest)(nil), "thirtyfive.ReleaseInventoryRequest")
	proto.RegisterType((*ReleaseInventoryReply)(nil), "thirtyfive.ReleaseInventoryReply")
	proto.RegisterEnum("thirtyfive.ShipmentStatus", ShipmentStatus_name, ShipmentStatus_value)
	proto.RegisterEnum("thirtyfive.ShipmentType", ShipmentType_name, ShipmentType_value)
	proto.RegisterEnum("thirtyfive.ShipmentDirection", ShipmentDirection_name, ShipmentDirection_value)
	proto.RegisterEnum("thirtyfive.InventoryCondition", InventoryCondition_name, InventoryCondition_value)
	proto.RegisterEnum("thirtyfive.InventoryStatus", InventoryStatus_name, InventoryStatus_value)
}

func init() { proto.RegisterFile("thirtyfive.proto", fileDescriptor_thirtyfive_af9745d5c07ca156) }

var fileDescriptor_thirtyfive_af9745d5c07ca156 = []byte{
	// 1260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0x75, 0xb2, 0x39, 0x4a, 0xec, 0xcd, 0xe6, 0x60, 0xfe, 0xf2, 0x21, 0x8a, 0x7e, 0x17,
	0x35, 0xdc, 0x40, 0x09, 0x94, 0xcb, 0x16, 0x05, 0x64, 0x69, 0xed, 0x10, 0x91, 0x49, 0x75, 0x45,
	0xda, 0x2d, 0x50, 0x40, 0x60, 0xc4, 0x8d, 0x4d, 0x54, 0x12, 0x55, 0x72, 0x65, 0x40, 0x4f, 0x53,
	0xa0, 0x2f, 0x50, 0xf4, 0x2d, 0xfa, 0x14, 0xed, 0x6d, 0x1f, 0xa3, 0x58, 0x1e, 0x44, 0x8a, 0xa2,
	0x92, 0x02, 0xb9, 0xed, 0x9d, 0x76, 0xbe, 0x6f, 0xbf, 0x99, 0x9d, 0xf9, 0xc8, 0xa5, 0x00, 0xf1,
	0x3b, 0xc7, 0xe3, 0x8b, 0x0f, 0xce, 0x3d, 0x6b, 0xce, 0x3c, 0x97, 0xbb, 0x18, 0x92, 0x48, 0xed,
	0xf9, 0xad, 0xeb, 0xde, 0x8e, 0xd9, 0xab, 0x00, 0x79, 0x3f, 0xff, 0xf0, 0x8a, 0x3b, 0x13, 0xe6,
	0x73, 0x6b, 0x32, 0x0b, 0xc9, 0x8d, 0xbf, 0x0a, 0xb0, 0x33, 0xb8, 0x73, 0x66, 0x13, 0x36, 0xe5,
	0x78, 0x17, 0x0a, 0x8e, 0xad, 0x48, 0x75, 0xe9, 0x54, 0xa6, 0x05, 0xc7, 0xc6, 0x17, 0xf0, 0x88,
	0xf9, 0x7c, 0x68, 0xb3, 0xb1, 0x73, 0xcf, 0xbc, 0xc5, 0xd0, 0xb6, 0x38, 0x53, 0x0a, 0x75, 0xe9,
	0xb4, 0xda, 0xaa, 0x35, 0x43, 0xe5, 0x66, 0xac, 0xdc, 0x34, 0x62, 0x65, 0xba, 0xc7, 0x7c, 0xde,
	0x8d, 0xf6, 0x74, 0x2d, 0xce, 0xf0, 0x97, 0xb0, 0xe7, 0x4c, 0xef, 0xd9, 0x94, 0xbb, 0xde, 0x62,
	0x38, 0x72, 0xe7, 0x53, 0xae, 0x14, 0xeb, 0xd2, 0x69, 0x99, 0xee, 0x2e, 0xc3, 0x1d, 0x11, 0xc5,
	0x2d, 0xa8, 0xf8, 0xdc, 0xe2, 0x73, 0x5f, 0x29, 0xd5, 0xa5, 0xd3, 0xdd, 0x56, 0xad, 0x99, 0x3a,
	0x5d, 0x5c, 0xe6, 0x20, 0x60, 0xd0, 0x88, 0x89, 0xbf, 0x06, 0xd9, 0x76, 0x3c, 0x36, 0xe2, 0x8e,
	0x3b, 0x55, 0xca, 0xc1, 0xb6, 0xa3, 0xbc, 0x6d, 0xdd, 0x98, 0x44, 0x13, 0x3e, 0x7e, 0x09, 0x25,
	0xbe, 0x98, 0x31, 0xa5, 0x12, 0xec, 0x53, 0xf2, 0xf6, 0x19, 0x8b, 0x19, 0xa3, 0x01, 0x0b, 0xbf,
	0x01, 0x79, 0x59, 0xb0, 0xb2, 0x5d, 0x2f, 0x9e, 0x56, 0x5b, 0x4f, 0xd3, 0x5b, 0xd4, 0x18, 0xa4,
	0x09, 0xaf, 0xd1, 0x83, 0x07, 0xb1, 0x94, 0xe6, 0xda, 0x6c, 0xad, 0xc9, 0x2f, 0xa1, 0xe2, 0xb1,
	0x91, 0xeb, 0xd9, 0x41, 0x4f, 0xaa, 0xad, 0x27, 0x79, 0x45, 0xd0, 0x88, 0xd3, 0xf8, 0x53, 0x02,
	0x79, 0x99, 0x66, 0x4d, 0x0b, 0x41, 0xf1, 0xbd, 0x33, 0x0d, 0x46, 0x24, 0x53, 0xf1, 0x13, 0x3f,
	0x83, 0x8a, 0xcf, 0x3c, 0xc7, 0x1a, 0x07, 0xea, 0x32, 0x8d, 0x56, 0xf8, 0x04, 0x4a, 0x73, 0x9f,
	0x79, 0x41, 0x9f, 0xab, 0x2d, 0x94, 0xce, 0x69, 0xfa, 0xcc, 0xa3, 0x01, 0x8a, 0xdf, 0x2c, 0xe7,
	0x11, 0x36, 0xf6, 0x20, 0xf7, 0xb4, 0x99, 0x81, 0x7c, 0x03, 0xf2, 0xc8, 0x9d, 0xda, 0x4e, 0x30,
	0x90, 0xb0, 0xb1, 0xc7, 0xb9, 0xfb, 0x3a, 0x31, 0x8b, 0x26, 0x1b, 0x1a, 0xd7, 0x50, 0x12, 0x05,
	0xac, 0x1d, 0x0d, 0x43, 0x69, 0x6a, 0x4d, 0x58, 0x74, 0xb6, 0xe0, 0x37, 0x7e, 0x02, 0x65, 0x36,
	0xb1, 0x9c, 0xf8, 0x6c, 0xe1, 0x42, 0x44, 0x67, 0x77, 0xee, 0x94, 0x05, 0x67, 0x93, 0x69, 0xb8,
	0x68, 0xfc, 0x5a, 0x00, 0x50, 0xa7, 0xfe, 0x2c, 0x1a, 0x7c, 0x56, 0xfe, 0x04, 0x1e, 0x7e, 0x98,
	0x4f, 0x03, 0xcc, 0x1a, 0x3b, 0x7c, 0x11, 0xe4, 0x29, 0xd3, 0xd5, 0x20, 0x3e, 0x04, 0xd9, 0x62,
	0xfc, 0x8e, 0xf9, 0xdc, 0x19, 0x45, 0x16, 0x4e, 0x02, 0x22, 0xb1, 0x33, 0xb1, 0x6e, 0x97, 0x89,
	0x83, 0x85, 0x88, 0x4e, 0x5d, 0xce, 0xc2, 0x16, 0xca, 0x34, 0x5c, 0x7c, 0x5e, 0x93, 0x70, 0x1d,
	0xaa, 0x4b, 0x83, 0xa9, 0xb6, 0xb2, 0x1d, 0x28, 0xa7, 0x43, 0xf8, 0x18, 0xc0, 0x8f, 0xbc, 0xa3,
	0xda, 0xca, 0x4e, 0x40, 0x48, 0x45, 0x44, 0x55, 0xdc, 0xf2, 0x7f, 0xf2, 0x15, 0x39, 0xac, 0x2a,
	0x58, 0x34, 0x3a, 0xf0, 0xf8, 0x92, 0xf1, 0xd8, 0x74, 0x3e, 0x65, 0x3f, 0xcf, 0x99, 0xcf, 0x05,
	0xd9, 0xf5, 0x6c, 0xe6, 0x45, 0xfd, 0x0a, 0x17, 0xc2, 0x5a, 0x23, 0x77, 0x3c, 0x9f, 0xc4, 0x7e,
	0x8b, 0x56, 0x8d, 0x4b, 0x78, 0xb4, 0x2a, 0x32, 0x1b, 0x2f, 0x70, 0x0b, 0xe4, 0x38, 0xbb, 0xaf,
	0x48, 0xc1, 0xa3, 0x93, 0x6f, 0xf4, 0x84, 0xd6, 0x38, 0x01, 0x9c, 0x12, 0x8a, 0x8b, 0xc9, 0x4c,
	0xae, 0x61, 0x00, 0x5a, 0x61, 0x89, 0x6c, 0xd9, 0xe9, 0xbe, 0x86, 0x9d, 0x58, 0x36, 0x7a, 0x7f,
	0xe5, 0x27, 0x5f, 0xb2, 0x1a, 0xbf, 0x14, 0x60, 0xbf, 0xe3, 0x31, 0x8b, 0xb3, 0xc4, 0x34, 0x71,
	0x05, 0x6b, 0x5e, 0x91, 0x3e, 0xe9, 0x95, 0xc2, 0x46, 0xaf, 0x14, 0x73, 0xbd, 0x52, 0xda, 0xe8,
	0x95, 0xf2, 0x67, 0x7a, 0xa5, 0xf2, 0x29, 0xaf, 0x6c, 0x6f, 0xf6, 0xca, 0x4e, 0xbd, 0x98, 0x78,
	0x45, 0x74, 0xc8, 0x9c, 0xd9, 0xff, 0x75, 0x68, 0x63, 0x87, 0xbe, 0x82, 0x7d, 0xca, 0xc6, 0xcc,
	0xf2, 0x59, 0x72, 0x31, 0x44, 0x0d, 0x42, 0x50, 0x74, 0xec, 0xf0, 0x41, 0x90, 0xa9, 0xf8, 0xd9,
	0xe8, 0xc1, 0xd3, 0x75, 0xb2, 0xf0, 0xf2, 0xca, 0xa5, 0x23, 0xfd, 0xbb, 0x4b, 0xe7, 0xec, 0x8f,
	0x02, 0xec, 0xae, 0xde, 0x97, 0xb8, 0x06, 0xcf, 0x56, 0x23, 0x43, 0x53, 0x7b, 0xa7, 0xe9, 0x37,
	0x1a, 0xda, 0xc2, 0x47, 0xf0, 0xbf, 0x0c, 0xd6, 0xa7, 0xc4, 0xa0, 0x6d, 0x6d, 0xa0, 0x1a, 0x48,
	0xc2, 0x87, 0xa0, 0x64, 0x60, 0x55, 0x8b, 0xd1, 0x02, 0x7e, 0x01, 0x47, 0x19, 0x54, 0x37, 0x8d,
	0x0b, 0x9d, 0x76, 0x49, 0x4f, 0xbd, 0x26, 0xf4, 0x07, 0x54, 0xcc, 0x11, 0x88, 0x40, 0xd2, 0x45,
	0x25, 0xfc, 0x05, 0xbc, 0xc8, 0xa0, 0xed, 0xeb, 0xb6, 0xda, 0x6b, 0x9f, 0xf7, 0xc8, 0x85, 0x4e,
	0xfb, 0x6a, 0xe7, 0x9d, 0xd9, 0x47, 0xe5, 0x9c, 0x3c, 0x94, 0x18, 0x26, 0xd5, 0x0c, 0x7d, 0x40,
	0xb4, 0x2e, 0xa1, 0xa8, 0x92, 0x73, 0xc6, 0x8b, 0xb6, 0xda, 0x33, 0x29, 0x41, 0xdb, 0x39, 0x35,
	0x74, 0xda, 0x5a, 0x87, 0xf4, 0x7a, 0xa4, 0x8b, 0x76, 0xb0, 0x02, 0x4f, 0x32, 0x28, 0xa1, 0x54,
	0xa7, 0x48, 0x3e, 0xfb, 0x36, 0xb9, 0xbf, 0xc5, 0xa7, 0x00, 0xde, 0x87, 0xc7, 0xe9, 0xf5, 0xb0,
	0xdd, 0xe9, 0x90, 0xc1, 0x00, 0x6d, 0xe1, 0xa7, 0xf0, 0x68, 0x05, 0x20, 0x6d, 0xaa, 0x21, 0xe9,
	0x8c, 0x26, 0xe1, 0xe5, 0x27, 0x48, 0xba, 0xe1, 0xcb, 0xe0, 0x50, 0xd5, 0xce, 0x75, 0x53, 0xeb,
	0xa2, 0x2d, 0x7c, 0x0c, 0xb5, 0x75, 0x58, 0x37, 0x8d, 0x10, 0x97, 0xce, 0x7e, 0x93, 0x00, 0xaf,
	0x7b, 0x5a, 0x1c, 0x7f, 0x3d, 0x3a, 0xd4, 0xc8, 0x4d, 0x28, 0x99, 0x83, 0xf5, 0xd4, 0x77, 0x44,
	0xe0, 0x12, 0xae, 0xc3, 0x61, 0x0e, 0x4e, 0xbe, 0x0f, 0x3a, 0xa4, 0x89, 0x39, 0x1f, 0xc0, 0x7e,
	0x0e, 0xc3, 0x1c, 0x90, 0x2e, 0x2a, 0x6e, 0x90, 0xef, 0xb6, 0xaf, 0xda, 0x97, 0x62, 0xc6, 0x67,
	0x7f, 0x17, 0x61, 0x2f, 0xf3, 0xc1, 0x20, 0x3a, 0x99, 0x09, 0x45, 0xb5, 0xa6, 0x33, 0xc5, 0x7e,
	0x24, 0x5a, 0x57, 0xd5, 0x2e, 0x43, 0x33, 0x66, 0x41, 0x31, 0x82, 0xbe, 0x41, 0xba, 0xa8, 0x80,
	0x4f, 0xa0, 0x9e, 0x45, 0x89, 0x46, 0x75, 0xd3, 0x20, 0x37, 0x6d, 0x4a, 0xde, 0xea, 0xe6, 0x80,
	0x64, 0xaa, 0x5d, 0x3a, 0x7a, 0xd0, 0x27, 0x1d, 0x43, 0xe4, 0x28, 0xe1, 0xe7, 0x70, 0xb0, 0x8e,
	0x27, 0x02, 0xe5, 0x95, 0x6e, 0x45, 0x84, 0xc1, 0x5b, 0xb5, 0x7f, 0x45, 0x34, 0xa3, 0x4f, 0x49,
	0x1f, 0x55, 0x84, 0x5b, 0x37, 0x14, 0x72, 0x45, 0xae, 0xce, 0x09, 0x45, 0xdb, 0x79, 0x55, 0xdc,
	0xa8, 0xc6, 0xdb, 0x08, 0xdf, 0x11, 0x26, 0xc9, 0xe2, 0xa1, 0xe3, 0x45, 0x91, 0x72, 0x5e, 0x0d,
	0xba, 0x69, 0xe8, 0x17, 0x03, 0x42, 0xaf, 0xd5, 0x0e, 0x41, 0x90, 0xc7, 0x88, 0x6a, 0xd0, 0x6f,
	0x34, 0x42, 0x51, 0x35, 0xaf, 0x99, 0x61, 0x0a, 0xd2, 0x45, 0x0f, 0x56, 0xfc, 0x14, 0x9f, 0xd2,
	0xd0, 0x7b, 0x44, 0x43, 0x0f, 0xc5, 0x03, 0x93, 0xc5, 0x7a, 0xfa, 0xc0, 0x40, 0xbb, 0xad, 0xdf,
	0x8b, 0x00, 0x46, 0xf0, 0x7e, 0xba, 0x70, 0xee, 0x19, 0xee, 0xc3, 0x83, 0xf4, 0xe7, 0x00, 0x7e,
	0x9e, 0x7e, 0x79, 0xe5, 0x7c, 0x6d, 0xd4, 0x8e, 0x36, 0x13, 0x66, 0xe3, 0x45, 0x63, 0x0b, 0x5f,
	0x41, 0x35, 0x15, 0xc6, 0xc7, 0x1b, 0xf8, 0xb1, 0xde, 0xe1, 0x46, 0x3c, 0x94, 0xfb, 0x0e, 0x50,
	0xf6, 0xa6, 0xc7, 0xff, 0x4f, 0xef, 0xd9, 0xf0, 0x1d, 0x50, 0x7b, 0xb6, 0xfa, 0x1a, 0x8e, 0xe1,
	0x50, 0x32, 0x7b, 0x35, 0xae, 0x4a, 0x6e, 0xb8, 0x38, 0x3f, 0x22, 0xf9, 0x23, 0xa0, 0xec, 0xfd,
	0xb0, 0x2a, 0xb9, 0xe1, 0xaa, 0xa9, 0xbd, 0xf8, 0x38, 0x29, 0xe8, 0xc1, 0xf9, 0x6b, 0x38, 0x70,
	0xdc, 0xe6, 0xad, 0x37, 0x1b, 0x35, 0x67, 0x96, 0x67, 0x8d, 0xee, 0xe6, 0x3c, 0xb5, 0xed, 0x7c,
	0x2f, 0x99, 0x67, 0x5f, 0xfc, 0xdf, 0xeb, 0x4b, 0xef, 0x2b, 0xc1, 0x1f, 0xbf, 0x37, 0xff, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x0f, 0xaa, 0x7b, 0x61, 0x80, 0x0e, 0x00, 0x00,
}
